### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by smuaq** [Playfrog4u/OpenTok-Ionic#1]
Hi, As expected its not going to work on IOS due to the fact that webrtc support is still not in.

**Comment by Playfrog4u** [comment]
Hello @smuaq I actually got a working version of Opentok and ionic working, I'll push a update soon 😄

**Comment by smuaq** [comment]
@Playfrog4u Ionic 3? I have it working on Ionic 1 & I was looking for some pointers to get it up on the lastest version
